export const LOGIN_EMAIL = 'LOGIN_EMAIL';
export const CHANGE_AUTH_STATUS = 'CHANGE_AUTH_STATUS';
export const LOG_OUT = 'LOG_OUT';

export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const ADD_SEARCH = 'ADD_SEARCH';
export const REMOVE_SEARCH = 'REMOVE_SEARCH';