export const LOGIN_EMAIL = 'LOGIN_EMAIL';
export const CHANGE_AUTH_STATUS = 'CHANGE_AUTH_STATUS';
export const LOG_OUT = 'LOG_OUT';

export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const ADD_SEARCH = 'ADD_SEARCH';
export const REMOVE_SEARCH = 'REMOVE_SEARCH';

export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const ADD_CLASS_TAKEN = 'CLASS_TAKEN';
export const REMOVE_CLASS_TAKEN = 'REMOVE_CLASS_TAKEN';

export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const REMOVE_SCHEDULE = 'REMOVE_SCHEDULE';
export const ADD_CLASS_TO_SCHEDULE = 'ADD_CLASS_TO_SCHEDULE';
export const REMOVE_CLASS_FROM_SCHEDULE = 'REMOVE_CLASS_FROM_SCHEDULE';